version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/mrEverything
    overwrite: yes

permissions:
  - object: /home/ubuntu/mrEverything
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600